// apps/blog-nuxt/app/pages/verify-email.vue
<script setup lang="ts">
import { navigateTo, useRoute } from '#imports'
import { useAuth } from '@holo-js/auth/nuxt'
import { useForm } from '@holo-js/adapter-nuxt/client'
import { ref } from 'vue'
import { verifyEmailForm } from '#shared/schemas/auth'

const { refreshUser } = await useAuth()
const route = useRoute()
const token = typeof route.query.token === 'string' ? route.query.token : ''
const email = typeof route.query.email === 'string' ? route.query.email : ''
const resendMessage = ref('')
const resendError = ref('')
const resending = ref(false)

const form = useForm(verifyEmailForm, {
  initialValues: { token },
  async submitter({ formData }) {
    const submission = await $fetch('/api/verify-email', { method: 'POST', body: formData })
    if (submission?.ok === true && typeof submission.data?.redirectTo === 'string') {
      await refreshUser()
      await navigateTo(submission.data.redirectTo)
    }
    return submission
  },
})

async function resendVerificationEmail() {
  resending.value = true
  resendMessage.value = ''
  resendError.value = ''

  try {
    const payload = await $fetch('/api/verify-email/resend', {
      method: 'POST',
      body: email ? { email } : {},
    })
    if (payload?.ok === true) {
      resendMessage.value = payload.data?.message ?? 'A fresh verification email has been sent.'
      return
    }

    const message = Array.isArray(payload?.errors?._root)
      ? payload.errors._root[0]
      : 'Could not send another verification email.'
    resendError.value = typeof message === 'string' ? message : 'Could not send another verification email.'
  } catch {
    resendError.value = 'Could not send another verification email.'
  } finally {
    resending.value = false
  }
}
</script>

<template>
  <section class="panel">
    <div class="copy">
      <h1>Verify your email</h1>
      <p>Use the verification link from your inbox to confirm the account.</p>
    </div>

    <form v-if="token" class="stack" @submit.prevent="form.submit()">
      <input name="token" type="hidden" v-model="form.values.token">
      <span v-if="form.errors.has('token')" class="error">{{ form.errors.first('token') }}</span>
      <button :disabled="form.submitting">
        {{ form.submitting ? 'Verifying...' : 'Verify email' }}
      </button>
    </form>

    <div v-else class="stack">
      <p>
        {{ email
          ? `Check ${email} for the verification email, then open the link from this page.`
          : 'Check your inbox for the verification email, then open the link from this page.' }}
      </p>
      <button type="button" :disabled="resending" @click="resendVerificationEmail">
        {{ resending ? 'Sending...' : 'Resend verification email' }}
      </button>
      <p v-if="resendMessage" class="success">{{ resendMessage }}</p>
      <p v-if="resendError" class="error">{{ resendError }}</p>
    </div>

    <div v-if="form.lastSubmission?.ok === true" class="success">
      <p>Your email address has been verified.</p>
      <NuxtLink to="/login">Sign in</NuxtLink>
    </div>

    <div class="links">
      <NuxtLink to="/register">Create another account</NuxtLink>
      <NuxtLink to="/login">Back to sign in</NuxtLink>
    </div>
  </section>
</template>

<style scoped>
.panel { display: grid; gap: 1rem; max-width: 36rem; padding: 1.5rem; border-radius: 1rem; background: #111827; border: 1px solid rgba(148, 163, 184, 0.16); }
.copy p { margin: 0; color: #94a3b8; }
.stack { display: grid; gap: 0.9rem; }
.error { color: #fca5a5; margin: 0; }
.success { color: #86efac; }
.links { display: flex; gap: 1rem; flex-wrap: wrap; }
a { color: #7dd3fc; text-decoration: none; }
</style>

// apps/blog-sveltekit/src/routes/verify-email/+page.svelte
<script lang="ts">
  import { goto, invalidateAll } from '$app/navigation'
  import { useAuth, useForm } from '@holo-js/adapter-sveltekit/client'
  import { verifyEmailForm } from '$lib/schemas/auth'

  export let data: {
    email: string
    token: string
  }

  let resendMessage = ''
  let resendError = ''
  let resending = false

  const auth = useAuth()
  const form = useForm(verifyEmailForm, {
    initialValues: { token: data.token },
    async submitter({ formData }) {
      const response = await fetch('/api/verify-email', { method: 'POST', body: formData })
      const submission = await response.json()
      if (submission?.ok === true && typeof submission.data?.redirectTo === 'string') {
        await auth.refreshUser()
        await invalidateAll()
        await goto(submission.data.redirectTo)
      }
      return submission
    },
  })

  async function resendVerificationEmail() {
    resending = true
    resendMessage = ''
    resendError = ''

    try {
      const response = await fetch('/api/verify-email/resend', {
        method: 'POST',
        headers: {
          'content-type': 'application/json',
        },
        body: JSON.stringify(data.email ? { email: data.email } : {}),
      })
      const payload = await response.json()
      if (payload?.ok === true) {
        resendMessage = payload.data?.message ?? 'A fresh verification email has been sent.'
        return
      }

      const message = Array.isArray(payload?.errors?._root)
        ? payload.errors._root[0]
        : 'Could not send another verification email.'
      resendError = typeof message === 'string' ? message : 'Could not send another verification email.'
    } finally {
      resending = false
    }
  }
</script>

<section class="panel">
  <div class="copy">
    <h1>Verify your email</h1>
    <p>Use the verification link from your inbox to confirm the account.</p>
  </div>

  {#if data.token}
    <form class="stack" on:submit={(event) => { event.preventDefault(); form.submit() }}>
      <input name="token" type="hidden" value={form.values.token} />
      {#if form.errors.has('token')}
        <span class="error">{form.errors.first('token')}</span>
      {/if}
      <button disabled={form.submitting}>
        {form.submitting ? 'Verifying...' : 'Verify email'}
      </button>
    </form>
  {:else}
    <div class="stack">
      <p>
        {data.email
          ? `Check ${data.email} for the verification email, then open the link from this page.`
          : 'Check your inbox for the verification email, then open the link from this page.'}
      </p>
      <button type="button" disabled={resending} on:click={() => { void resendVerificationEmail() }}>
        {resending ? 'Sending...' : 'Resend verification email'}
      </button>
      {#if resendMessage}
        <p class="success">{resendMessage}</p>
      {/if}
      {#if resendError}
        <p class="error">{resendError}</p>
      {/if}
    </div>
  {/if}

  {#if form.lastSubmission?.ok === true}
    <div class="success">
      <p>Your email address has been verified.</p>
      <a href="/login">Sign in</a>
    </div>
  {/if}

  <div class="links">
    <a href="/register">Create another account</a>
    <a href="/login">Back to sign in</a>
  </div>
</section>

<style>
  .panel { display: grid; gap: 1rem; max-width: 36rem; padding: 1.5rem; border-radius: 1rem; background: #111827; border: 1px solid rgba(148, 163, 184, 0.16); }
  .copy p { margin: 0; color: #94a3b8; }
  .stack { display: grid; gap: 0.9rem; }
  .error { color: #fca5a5; margin: 0; }
  .success { color: #86efac; }
  .links { display: flex; gap: 1rem; flex-wrap: wrap; }
  .success a, .links a { color: #7dd3fc; text-decoration: none; }
</style>
