// apps/blog-next/app/posts/page.tsx
import Link from 'next/link'

import { getPublishedPosts } from '@/server/lib/blog'

export const dynamic = 'force-dynamic'

export default async function PostsPage() {
  const posts = await getPublishedPosts()

  return (
    <section style={{ display: 'grid', gap: '1rem' }}>
      <h1 style={{ margin: 0 }}>Posts</h1>
      {posts.map(post => (
        <article key={post.id} style={{ padding: '1.25rem', borderRadius: '1rem', background: '#111827', border: '1px solid rgba(148, 163, 184, 0.16)' }}>
          <h2 style={{ marginTop: 0 }}><Link href={`/posts/${post.slug}`} style={{ color: '#fff', textDecoration: 'none' }}>{post.title}</Link></h2>
          <p style={{ color: '#cbd5e1' }}>{post.excerpt}</p>
        </article>
      ))}
    </section>
  )
}

// apps/blog-nuxt/app/pages/posts/index.vue
<script setup lang="ts">
import type { PublishedPostsData } from '../../../server/lib/blog'

const { data } = await useFetch<PublishedPostsData>('/api/blog/posts')
</script>

<template>
  <section class="stack">
    <h1>Posts</h1>
    <article v-for="post in data || []" :key="post.id" class="panel">
      <h2><NuxtLink :to="`/posts/${post.slug}`">{{ post.title }}</NuxtLink></h2>
      <p>{{ post.excerpt }}</p>
    </article>
  </section>
</template>

<style scoped>
.stack { display: grid; gap: 1rem; }
.panel { padding: 1.25rem; border-radius: 1rem; background: #111827; }
</style>
