// apps/blog-next/app/admin/tags/page.tsx
import Link from 'next/link'
import { getAdminTagsData } from '@/server/lib/blog'
import { createTagAction, deleteTagAction } from '../actions'

export const dynamic = 'force-dynamic'

export default async function AdminTagsPage() {
  const data = await getAdminTagsData()

  return (
    <section style={{ display: 'grid', gap: '1.5rem' }}>
      <h1 style={{ margin: 0 }}>Tags</h1>
      <form action={createTagAction} style={{ display: 'grid', gap: '0.75rem' }}>
        <input name="name" placeholder="Tag name" required />
        <button type="submit">Create tag</button>
      </form>
      {data.tags.map(tag => (
        <article key={tag.id} style={{ padding: '1rem', borderRadius: '1rem', background: '#111827' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem' }}>
            <div>
              <strong>{tag.name}</strong>
              <div style={{ color: '#94a3b8' }}>{tag.slug}</div>
            </div>
            <div style={{ display: 'flex', gap: '0.75rem' }}>
              <Link href={`/admin/tags/${tag.id}/edit`} style={{ color: '#7dd3fc' }}>Edit</Link>
              <form action={deleteTagAction.bind(null, tag.id)}>
                <button type="submit">Delete</button>
              </form>
            </div>
          </div>
        </article>
      ))}
    </section>
  )
}

// apps/blog-nuxt/app/pages/admin/tags/index.vue
<script setup lang="ts">
import type { AdminTagsData } from '../../../../server/lib/blog'

const { data } = await useFetch<AdminTagsData>('/api/admin/tags')
</script>

<template>
  <section class="stack">
    <h1>Tags</h1>
    <form action="/admin/tags/create" method="post" class="stack">
      <input name="name" placeholder="Tag name" required>
      <button type="submit">Create tag</button>
    </form>
    <article v-for="tag in data?.tags || []" :key="tag.id" class="panel row">
      <div><strong>{{ tag.name }}</strong><div>{{ tag.slug }}</div></div>
      <div class="row">
        <NuxtLink :to="`/admin/tags/${tag.id}/edit`">Edit</NuxtLink>
        <form :action="`/admin/tags/${tag.id}/delete`" method="post"><button type="submit">Delete</button></form>
      </div>
    </article>
  </section>
</template>

<style scoped>
.stack { display: grid; gap: 1rem; }
.row { display: flex; justify-content: space-between; gap: 1rem; align-items: center; }
.panel { padding: 1rem; border-radius: 1rem; background: #111827; }
</style>
