// apps/blog-nuxt/app/pages/super-admin/index.vue
<script setup lang="ts">
import { useAuth } from '@holo-js/auth/nuxt'

definePageMeta({
  middleware: 'super-admin',
})

const { refreshUser, user } = await useAuth({ guard: 'admin' })
const displayName = computed(() => user.value?.name ?? user.value?.email ?? 'Super Admin')
const isLoggingOut = ref(false)

async function logout() {
  if (isLoggingOut.value) {
    return
  }

  isLoggingOut.value = true
  try {
    await $fetch('/api/super-admin/logout', { method: 'POST' })
    await refreshUser()
    await navigateTo('/super-admin/login')
  } catch (error) {
    console.warn('Super admin logout failed.', error)
  } finally {
    isLoggingOut.value = false
  }
}
</script>

<template>
  <section class="stack">
    <p class="eyebrow">Admin guard</p>
    <h1>Super Admin</h1>
    <p>Signed in as {{ displayName }} through the admin guard.</p>
    <div>
      <button type="button" :disabled="isLoggingOut" @click="logout">
        {{ isLoggingOut ? 'Signing out...' : 'Sign out of super admin' }}
      </button>
    </div>
  </section>
</template>

<style scoped>
.stack { display: grid; gap: 0.75rem; max-width: 42rem; }
.eyebrow { margin: 0; color: #7dd3fc; font-size: 0.875rem; text-transform: uppercase; }
h1 { margin: 0; }
p { margin: 0; color: #cbd5e1; }
</style>

// apps/blog-next/app/super-admin/page.tsx
import { redirect } from 'next/navigation'
import { auth } from '@holo-js/auth/next/server'
import { SuperAdminLogoutButton } from './logout-button'

export default async function SuperAdminPage() {
  const currentAuth = await auth({ guard: 'admin' })

  if (!currentAuth.authenticated) {
    redirect('/super-admin/login')
  }

  const displayName = currentAuth.user?.name ?? currentAuth.user?.email ?? 'Super Admin'

  return (
    <section style={{ display: 'grid', gap: '0.75rem', maxWidth: '42rem' }}>
      <p style={{ margin: 0, color: '#7dd3fc', fontSize: '0.875rem', textTransform: 'uppercase' }}>Admin guard</p>
      <h1 style={{ margin: 0 }}>Super Admin</h1>
      <p style={{ margin: 0, color: '#cbd5e1' }}>Signed in as {displayName} through the admin guard.</p>
      <div>
        <SuperAdminLogoutButton />
      </div>
    </section>
  )
}
