// apps/blog-nuxt/pages/posts/[slug].vue
<script setup lang="ts">
const route = useRoute()
const { data } = await useFetch(`/api/blog/posts/${route.params.slug}`)

if (!data.value) {
  throw createError({ statusCode: 404, statusMessage: 'Post not found' })
}
</script>

<template>
  <article class="stack">
    <NuxtLink to="/posts">Back to posts</NuxtLink>
    <h1>{{ data?.title }}</h1>
    <p>{{ data?.excerpt }}</p>
    <div class="panel">{{ data?.body }}</div>
  </article>
</template>

<style scoped>
.stack { display: grid; gap: 1rem; }
.panel { padding: 1.25rem; border-radius: 1rem; background: #111827; line-height: 1.8; }
</style>

// apps/blog-sveltekit/src/routes/posts/[slug]/+page.svelte
<script lang="ts">
  import { type PageData } from './$types'

  export let data: PageData
</script>

{#if data}
  <article class="stack">
    <a href="/posts">Back to posts</a>
    <h1>{data.post.title}</h1>
    <p>{data.post.excerpt}</p>
    <div class="panel">{data.post.body}</div>
  </article>
{/if}

<style>
  .stack { display: grid; gap: 1rem; }
  .panel { padding: 1.25rem; border-radius: 1rem; background: #111827; line-height: 1.8; }
</style>
