// apps/blog-sveltekit/src/routes/admin/+page.svelte
<script lang="ts">
  import { type PageData } from './$types'

  export let data: PageData
</script>

{#if data}
  <section class="stack">
    <h1>Admin</h1>
    <div class="grid">
      <article class="panel"><strong>{data.postCount}</strong><div>Posts</div></article>
      <article class="panel"><strong>{data.publishedCount}</strong><div>Published</div></article>
      <article class="panel"><strong>{data.categoryCount}</strong><div>Categories</div></article>
      <article class="panel"><strong>{data.tagCount}</strong><div>Tags</div></article>
    </div>
    <div class="links">
      <a href="/admin/posts">Manage posts</a>
      <a href="/admin/categories">Manage categories</a>
      <a href="/admin/tags">Manage tags</a>
    </div>
  </section>
{/if}

<style>
  .stack { display: grid; gap: 1rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr)); gap: 1rem; }
  .panel { padding: 1rem; border-radius: 1rem; background: #111827; }
  .links { display: flex; gap: 1rem; flex-wrap: wrap; }
  .links a { color: #7dd3fc; }
</style>

// apps/blog-next/app/admin/page.tsx
import Link from 'next/link'

import { getAdminDashboardData } from '@/server/lib/blog'

export const dynamic = 'force-dynamic'

export default async function AdminDashboardPage() {
  const dashboard = await getAdminDashboardData()

  return (
    <section style={{ display: 'grid', gap: '1rem' }}>
      <h1 style={{ margin: 0 }}>Admin</h1>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(12rem, 1fr))', gap: '1rem' }}>
        <article style={{ padding: '1rem', borderRadius: '1rem', background: '#111827' }}><strong>{dashboard.postCount}</strong><div>Posts</div></article>
        <article style={{ padding: '1rem', borderRadius: '1rem', background: '#111827' }}><strong>{dashboard.publishedCount}</strong><div>Published</div></article>
        <article style={{ padding: '1rem', borderRadius: '1rem', background: '#111827' }}><strong>{dashboard.categoryCount}</strong><div>Categories</div></article>
        <article style={{ padding: '1rem', borderRadius: '1rem', background: '#111827' }}><strong>{dashboard.tagCount}</strong><div>Tags</div></article>
      </div>
      <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
        <Link href="/admin/posts" style={{ color: '#7dd3fc' }}>Manage posts</Link>
        <Link href="/admin/categories" style={{ color: '#7dd3fc' }}>Manage categories</Link>
        <Link href="/admin/tags" style={{ color: '#7dd3fc' }}>Manage tags</Link>
      </div>
    </section>
  )
}
