// apps/blog-nuxt/app/pages/admin/posts/index.vue
<script setup lang="ts">
import type { AdminPostsData } from '../../../../server/lib/blog'

const { data } = await useFetch<AdminPostsData>('/api/admin/posts')
</script>

<template>
  <section class="stack">
    <div class="row"><h1>Posts</h1><NuxtLink to="/admin/posts/new">New post</NuxtLink></div>
    <article v-for="post in data?.posts || []" :key="post.id" class="panel row">
      <div>
        <h2>{{ post.title }}</h2>
        <p>{{ post.status }} · {{ post.category?.name || 'Uncategorized' }}</p>
      </div>
      <div class="row">
        <NuxtLink :to="`/admin/posts/${post.id}/edit`">Edit</NuxtLink>
        <form :action="`/admin/posts/${post.id}/delete`" method="post"><button type="submit">Delete</button></form>
      </div>
    </article>
  </section>
</template>

<style scoped>
.stack { display: grid; gap: 1rem; }
.row { display: flex; justify-content: space-between; gap: 1rem; align-items: center; }
.panel { padding: 1rem; border-radius: 1rem; background: #111827; }
</style>

// apps/blog-next/app/admin/posts/page.tsx
import Link from 'next/link'
import { getAdminPostsData } from '@/server/lib/blog'
import { deletePostAction } from '../actions'

export const dynamic = 'force-dynamic'

export default async function AdminPostsPage() {
  const data = await getAdminPostsData()

  return (
    <section style={{ display: 'grid', gap: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1 style={{ margin: 0 }}>Posts</h1>
        <Link href="/admin/posts/new" style={{ color: '#7dd3fc' }}>New post</Link>
      </div>
      {data.posts.map(post => (
        <article key={post.id} style={{ padding: '1.25rem', borderRadius: '1rem', background: '#111827' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'center' }}>
            <div>
              <h2 style={{ margin: '0 0 0.5rem 0' }}>{post.title}</h2>
              <div style={{ color: '#94a3b8' }}>{post.status} · {post.category?.name ?? 'Uncategorized'}</div>
            </div>
            <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center' }}>
              <Link href={`/admin/posts/${post.id}/edit`} style={{ color: '#7dd3fc' }}>Edit</Link>
              <form action={deletePostAction.bind(null, post.id)}>
                <button type="submit">Delete</button>
              </form>
            </div>
          </div>
        </article>
      ))}
    </section>
  )
}
