// apps/blog-sveltekit/src/routes/admin/categories/[id]/edit/+page.svelte
<script lang="ts">
  import { type PageData } from './$types'

  export let data: PageData
</script>

{#if data}
  <section class="stack">
    <h1>Edit category</h1>
    <form action="?/update" method="post" class="stack">
      <input name="name" value={data.category.name} required>
      <textarea name="description" rows="3">{data.category.description || ''}</textarea>
      <button type="submit">Save category</button>
    </form>
  </section>
{/if}

<style>
  .stack { display: grid; gap: 1rem; }
</style>

// apps/blog-next/app/admin/categories/[id]/edit/page.tsx
import { notFound } from 'next/navigation'
import { getAdminCategoryById } from '@/server/lib/blog'
import { updateCategoryAction } from '../../../actions'

export const dynamic = 'force-dynamic'

export default async function EditCategoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const category = await getAdminCategoryById(Number(id))

  if (!category) {
    notFound()
  }

  const updateWithId = updateCategoryAction.bind(null, category.id)

  return (
    <section style={{ display: 'grid', gap: '1rem' }}>
      <h1 style={{ margin: 0 }}>Edit category</h1>
      <form action={updateWithId} style={{ display: 'grid', gap: '0.75rem' }}>
        <input name="name" defaultValue={category.name} required />
        <textarea name="description" defaultValue={category.description ?? ''} rows={3} />
        <button type="submit">Save category</button>
      </form>
    </section>
  )
}
