// apps/blog-sveltekit/src/routes/admin/tags/[id]/edit/+page.svelte
<script lang="ts">
  import { type PageData } from './$types'

  export let data: PageData
</script>

{#if data}
  <section class="stack">
    <h1>Edit tag</h1>
    <form action={`/admin/tags/${data.tag.id}/update`} method="post" class="stack">
      <input name="name" value={data.tag.name} required>
      <button type="submit">Save tag</button>
    </form>
  </section>
{/if}

<style>
  .stack { display: grid; gap: 1rem; }
</style>

// apps/blog-nuxt/pages/admin/tags/[id]/edit.vue
<script setup lang="ts">
const route = useRoute()
const { data } = await useFetch(`/api/admin/tags/${route.params.id}`)

if (!data.value) {
  throw createError({ statusCode: 404, statusMessage: 'Tag not found' })
}
</script>

<template>
  <section class="stack">
    <h1>Edit tag</h1>
    <form :action="`/admin/tags/${data?.id}/update`" method="post" class="stack">
      <input name="name" :value="data?.name" required>
      <button type="submit">Save tag</button>
    </form>
  </section>
</template>

<style scoped>
.stack { display: grid; gap: 1rem; }
</style>
